### ISSUE TITLE
Create a Monorepo Structure

### ISSUE THREAD

**Issue by arantespp** [Joaopdev/MarketPlace#2]
### Description

This project will have many domains, and [monorepo](https://en.wikipedia.org/wiki/Monorepo) is the best repository structure to handle this. We can use [Yarn Workspaces](https://classic.yarnpkg.com/en/docs/workspaces/) to create our structure.

#### References

- [TTOSS Monorepo](https://github.com/ttoss/monorepo)
- [Sibelius Seraphini. Reducing testing and building time in Monorepos](https://sibelius.medium.com/reduce-testing-and-building-time-in-monorepos-5843b63972b)
- [Entria Fullstack Playground](https://github.com/entria/entria-fullstack)
- [golden-stack](https://github.com/FotonTech/golden-stack)

**Comment by Joaopdev** [comment]
Well, I spent the day divided between reading about the monorepos and putting it out there as I imagine the project's features.

I understood the idea, advantages and disadvantages (on a large scale) of monorepos, but I need to understand how the structure for our project will be created.

By the way, after reading so much long about monorepos, this subject will be my first thread on Twitter.
